name: ecosystem
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2.0
  - numpy>=2.1.0
  - scipy>=1.14.0
  - matplotlib>=3.9.0
  - geopandas>=1.0.0
  - rasterio>=1.3.10
  - jupyterlab>=4.2.0
