name: brain-imaging
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - numpy>=2.1
  - pandas>=2.2
  - matplotlib>=3.9
  - seaborn>=0.13
  - scipy>=1.14
  - scikit-learn>=1.5
  - nibabel>=5.2  # Neuroimaging file I/O
  - nilearn>=0.10  # fMRI analysis
  - plotly>=5.23
