name: crystal-structure
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - numpy>=2.1
  - pandas>=2.2
  - matplotlib>=3.9
  - seaborn>=0.13
  - scipy>=1.14
  - scikit-learn>=1.5
  - ase>=3.23  # Atomic Simulation Environment
  - pymatgen>=2024.10  # Materials analysis
  - plotly>=5.23
