name: behavioral
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2.0
  - numpy>=2.1.0
  - scipy>=1.14.0
  - scikit-learn>=1.5.0
  - statsmodels>=0.14.0
  - matplotlib>=3.9.0
  - seaborn>=0.13.0
  - jupyterlab>=4.2.0
  - pip:
    - factor-analyzer>=0.4.0
